-- Generated from ChartDB diagram: TAXAI
-- Database: postgresql

-- ============ ENUM TYPES ============
CREATE TYPE audit_action AS ENUM ('create', 'update', 'delete', 'login', 'logout');
CREATE TYPE auth_provider AS ENUM ('local', 'google', 'microsoft');
CREATE TYPE billing_cycle AS ENUM ('monthly', 'annual');
CREATE TYPE case_status AS ENUM ('open', 'closed', 'archived');
CREATE TYPE document_status AS ENUM ('uploaded', 'processing', 'indexed', 'error');
CREATE TYPE entity_type AS ENUM ('individual', 'company', 'association', 'public_body');
CREATE TYPE message_role AS ENUM ('user', 'ai', 'system');
CREATE TYPE monitoring_frequency AS ENUM ('daily', 'weekly', 'monthly');
CREATE TYPE monitoring_status AS ENUM ('active', 'paused');
CREATE TYPE notification_channel AS ENUM ('email', 'in_app');
CREATE TYPE notification_status AS ENUM ('pending', 'sent', 'failed');
CREATE TYPE permission_action AS ENUM ('list', 'create', 'read', 'update', 'delete');
CREATE TYPE permission_resource AS ENUM ('tenant', 'user', 'legal_entity', 'case', 'document', 'chat', 'monitored_case', 'probabilistic_estimate', 'subscription', 'settings');
CREATE TYPE probability_category AS ENUM ('highly_probable', 'probable', 'possible', 'unlikely');
CREATE TYPE subscription_status AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'unpaid');
CREATE TYPE subscription_type AS ENUM ('basic', 'advanced');
CREATE TYPE tenant_status AS ENUM ('active', 'inactive', 'pending', 'suspended');
CREATE TYPE user_role AS ENUM ('admin_site', 'admin_org', 'user');
CREATE TYPE user_status AS ENUM ('active', 'inactive', 'pending', 'suspended');

-- ============ TABLES ============
CREATE TABLE notification_template (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  channel notification_channel NOT NULL DEFAULT 'email',
  subject text,
  body_template text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_template_pkey PRIMARY KEY (id)
);

CREATE TABLE subscription_plan (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  type subscription_type NOT NULL,
  billing_cycle billing_cycle NOT NULL,
  price_cents integer NOT NULL,
  max_users integer NOT NULL DEFAULT 1,
  max_monitored_cases integer NOT NULL DEFAULT 3,
  max_estimates_per_month integer NOT NULL DEFAULT 10,
  max_document_size_mb integer NOT NULL DEFAULT 50,
  features jsonb,
  stripe_price_id text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subscription_plan_pkey PRIMARY KEY (id)
);

CREATE TABLE monitoring_update (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  monitored_case_id integer NOT NULL,
  summary text,
  content jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  checked_at timestamptz NOT NULL DEFAULT now(),
  processing_time_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT monitoring_update_pkey PRIMARY KEY (id)
);

CREATE TABLE tenant_case_counter (
  tenant_id integer NOT NULL,
  last_number integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_case_counter_pkey PRIMARY KEY (tenant_id)
);

CREATE TABLE scheduled_job (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  job_type text NOT NULL,
  reference_id integer,
  status text NOT NULL DEFAULT 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scheduled_job_pkey PRIMARY KEY (id)
);

CREATE TABLE chat_message (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id integer NOT NULL,
  "role" message_role NOT NULL,
  content text NOT NULL,
  sources jsonb,
  token_count integer,
  processing_time_ms integer,
  attachments jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chat_message_pkey PRIMARY KEY (id)
);

CREATE TABLE permission (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_value text NOT NULL,
  resource permission_resource NOT NULL,
  action permission_action NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT permission_pkey PRIMARY KEY (id)
);

CREATE TABLE "role" (
  value text NOT NULL,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT role_pkey PRIMARY KEY (value)
);

CREATE TABLE "case" (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  legal_entity_id integer NOT NULL,
  created_by integer NOT NULL,
  case_number text NOT NULL,
  title text NOT NULL,
  description text,
  assigned_lawyer integer,
  case_type text,
  status case_status NOT NULL DEFAULT 'open',
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT case_pkey PRIMARY KEY (id)
);

CREATE TABLE tenant (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  vat_number text,
  fiscal_code text,
  email text,
  phone text,
  address text,
  city text,
  province text,
  postal_code text,
  country text DEFAULT 'IT',
  status tenant_status NOT NULL DEFAULT 'pending',
  subscription_plan_id integer,
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status subscription_status,
  subscription_started_at timestamptz,
  subscription_expires_at timestamptz,
  trial_ends_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

CREATE TABLE stripe_webhook_event (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  stripe_event_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamptz,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stripe_webhook_event_pkey PRIMARY KEY (id)
);

CREATE TABLE chat_session (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  user_id integer NOT NULL,
  case_id integer,
  legal_entity_id integer,
  title text,
  context_snapshot jsonb NOT NULL,
  last_message_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chat_session_pkey PRIMARY KEY (id)
);

CREATE TABLE monitored_case (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  legal_entity_id integer NOT NULL,
  created_by integer NOT NULL,
  case_id integer,
  scenario text NOT NULL,
  frequency monitoring_frequency NOT NULL DEFAULT 'weekly',
  status monitoring_status NOT NULL DEFAULT 'active',
  last_checked_at timestamptz,
  next_check_at timestamptz,
  total_updates integer NOT NULL DEFAULT 0,
  unread_updates integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT monitored_case_pkey PRIMARY KEY (id)
);

CREATE TABLE probabilistic_estimate (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  legal_entity_id integer NOT NULL,
  case_id integer,
  created_by integer NOT NULL,
  description text NOT NULL,
  score double precision NOT NULL,
  category probability_category NOT NULL,
  analysis text,
  sources jsonb,
  recalculation_count integer NOT NULL DEFAULT 0,
  last_recalculated_at timestamptz,
  next_recalculation_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT probabilistic_estimate_pkey PRIMARY KEY (id)
);

CREATE TABLE legal_entity (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  type entity_type NOT NULL,
  name text NOT NULL,
  surname text,
  fiscal_code text,
  vat_number text,
  email text,
  phone text,
  address text,
  city text,
  province text,
  postal_code text,
  country text DEFAULT 'IT',
  notes text,
  created_by integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT legal_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE user_session (
  id uuid NOT NULL,
  user_id integer NOT NULL,
  ip_address text,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_session_pkey PRIMARY KEY (id)
);

CREATE TABLE estimate_history (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  estimate_id integer NOT NULL,
  score double precision NOT NULL,
  previous_score double precision,
  category probability_category NOT NULL,
  previous_category probability_category,
  analysis text,
  sources jsonb,
  score_delta double precision,
  is_significant_change boolean NOT NULL DEFAULT false,
  calculated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT estimate_history_pkey PRIMARY KEY (id)
);

CREATE TABLE notification_event (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_id integer NOT NULL,
  recipient_user_id integer NOT NULL,
  channel notification_channel NOT NULL DEFAULT 'email',
  subject text,
  body text,
  context jsonb,
  status notification_status NOT NULL DEFAULT 'pending',
  sent_at timestamptz,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_event_pkey PRIMARY KEY (id)
);

CREATE TABLE "user" (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  email text NOT NULL,
  password_hash text,
  name text NOT NULL,
  surname text NOT NULL,
  "role" user_role NOT NULL DEFAULT 'user',
  status user_status NOT NULL DEFAULT 'pending',
  auth_provider auth_provider NOT NULL DEFAULT 'local',
  auth_provider_id text,
  professional_role text,
  about text,
  profile_completion_pct integer NOT NULL DEFAULT 0,
  email_verified boolean NOT NULL DEFAULT false,
  email_verification_code text,
  email_verification_expires_at timestamptz,
  password_reset_code text,
  password_reset_expires_at timestamptz,
  last_login_at timestamptz,
  is_first_login boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE document (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id integer NOT NULL,
  uploaded_by integer NOT NULL,
  legal_entity_id integer,
  case_id integer,
  title text NOT NULL,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  file_size_bytes bigint,
  storage_key text NOT NULL,
  embedding_status document_status NOT NULL DEFAULT 'uploaded',
  embedding_id text,
  embedding_error text,
  indexed_at timestamptz,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT document_pkey PRIMARY KEY (id)
);

-- ============ INDEXES ============
CREATE UNIQUE INDEX subscription_plan_stripe_price_uq ON subscription_plan (stripe_price_id);
CREATE INDEX monitoring_update_case_idx ON monitoring_update (monitored_case_id);
CREATE INDEX monitoring_update_checked_idx ON monitoring_update (checked_at);
CREATE INDEX monitoring_update_unread_idx ON monitoring_update (monitored_case_id, is_read);
CREATE INDEX scheduled_job_type_ref_idx ON scheduled_job (job_type, reference_id);
CREATE INDEX scheduled_job_status_idx ON scheduled_job (status);
CREATE INDEX scheduled_job_retry_idx ON scheduled_job (next_retry_at);
CREATE INDEX chat_message_session_idx ON chat_message (session_id);
CREATE INDEX chat_message_created_idx ON chat_message (created_at);
CREATE UNIQUE INDEX permission_role_resource_action_uq ON permission (role_value, resource, action);
CREATE INDEX case_tenant_idx ON "case" (tenant_id);
CREATE INDEX case_legal_entity_idx ON "case" (legal_entity_id);
CREATE UNIQUE INDEX case_tenant_number_uq ON "case" (tenant_id, case_number);
CREATE INDEX case_status_idx ON "case" (status);
CREATE INDEX case_assigned_lawyer_idx ON "case" (assigned_lawyer);
CREATE UNIQUE INDEX tenant_stripe_customer_uq ON tenant (stripe_customer_id);
CREATE UNIQUE INDEX tenant_stripe_subscription_uq ON tenant (stripe_subscription_id);
CREATE INDEX tenant_status_idx ON tenant (status);
CREATE UNIQUE INDEX stripe_webhook_event_stripe_id_uq ON stripe_webhook_event (stripe_event_id);
CREATE INDEX stripe_webhook_event_type_processed_idx ON stripe_webhook_event (event_type, processed);
CREATE INDEX chat_session_tenant_idx ON chat_session (tenant_id);
CREATE INDEX chat_session_user_idx ON chat_session (user_id);
CREATE INDEX chat_session_case_idx ON chat_session (case_id);
CREATE INDEX chat_session_last_message_idx ON chat_session (last_message_at);
CREATE INDEX monitored_case_tenant_idx ON monitored_case (tenant_id);
CREATE INDEX monitored_case_legal_entity_idx ON monitored_case (legal_entity_id);
CREATE INDEX monitored_case_status_idx ON monitored_case (status);
CREATE INDEX monitored_case_next_check_idx ON monitored_case (next_check_at);
CREATE INDEX monitored_case_case_idx ON monitored_case (case_id);
CREATE INDEX probabilistic_estimate_tenant_idx ON probabilistic_estimate (tenant_id);
CREATE INDEX probabilistic_estimate_legal_entity_idx ON probabilistic_estimate (legal_entity_id);
CREATE INDEX probabilistic_estimate_case_idx ON probabilistic_estimate (case_id);
CREATE INDEX probabilistic_estimate_category_idx ON probabilistic_estimate (category);
CREATE INDEX probabilistic_estimate_next_recalc_idx ON probabilistic_estimate (next_recalculation_at);
CREATE INDEX legal_entity_tenant_idx ON legal_entity (tenant_id);
CREATE INDEX legal_entity_type_idx ON legal_entity (type);
CREATE INDEX legal_entity_fiscal_code_idx ON legal_entity (fiscal_code);
CREATE INDEX user_session_user_idx ON user_session (user_id);
CREATE INDEX user_session_expires_idx ON user_session (expires_at);
CREATE INDEX estimate_history_estimate_idx ON estimate_history (estimate_id);
CREATE INDEX estimate_history_calculated_idx ON estimate_history (calculated_at);
CREATE INDEX notification_event_template_idx ON notification_event (template_id);
CREATE INDEX notification_event_recipient_idx ON notification_event (recipient_user_id);
CREATE INDEX notification_event_status_idx ON notification_event (status);
CREATE INDEX notification_event_created_idx ON notification_event (created_at);
CREATE UNIQUE INDEX user_tenant_email_uq ON "user" (tenant_id, email);
CREATE INDEX user_tenant_idx ON "user" (tenant_id);
CREATE INDEX user_email_idx ON "user" (email);
CREATE INDEX user_status_idx ON "user" (status);
CREATE INDEX document_tenant_idx ON document (tenant_id);
CREATE INDEX document_uploaded_by_idx ON document (uploaded_by);
CREATE INDEX document_legal_entity_idx ON document (legal_entity_id);
CREATE INDEX document_case_idx ON document (case_id);
CREATE INDEX document_embedding_status_idx ON document (embedding_status);

-- ============ FOREIGN KEYS ============
ALTER TABLE "case" ADD CONSTRAINT case_assigned_lawyer_user_id FOREIGN KEY (assigned_lawyer) REFERENCES "user" (id);
ALTER TABLE "case" ADD CONSTRAINT case_created_by_user_id FOREIGN KEY (created_by) REFERENCES "user" (id);
ALTER TABLE "case" ADD CONSTRAINT case_legal_entity_id_legal_entity_id FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id);
ALTER TABLE "case" ADD CONSTRAINT case_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE chat_message ADD CONSTRAINT chat_message_session_id_chat_session_id FOREIGN KEY (session_id) REFERENCES chat_session (id);
ALTER TABLE chat_session ADD CONSTRAINT chat_session_case_id_case_id FOREIGN KEY (case_id) REFERENCES "case" (id);
ALTER TABLE chat_session ADD CONSTRAINT chat_session_legal_entity_id_legal_entity_id FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id);
ALTER TABLE chat_session ADD CONSTRAINT chat_session_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE chat_session ADD CONSTRAINT chat_session_user_id_user_id FOREIGN KEY (user_id) REFERENCES "user" (id);
ALTER TABLE document ADD CONSTRAINT document_case_id_case_id FOREIGN KEY (case_id) REFERENCES "case" (id);
ALTER TABLE document ADD CONSTRAINT document_legal_entity_id_legal_entity_id FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id);
ALTER TABLE document ADD CONSTRAINT document_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE document ADD CONSTRAINT document_uploaded_by_user_id FOREIGN KEY (uploaded_by) REFERENCES "user" (id);
ALTER TABLE estimate_history ADD CONSTRAINT estimate_history_estimate_id_probabilistic_estimate_id FOREIGN KEY (estimate_id) REFERENCES probabilistic_estimate (id);
ALTER TABLE legal_entity ADD CONSTRAINT legal_entity_created_by_user_id FOREIGN KEY (created_by) REFERENCES "user" (id);
ALTER TABLE legal_entity ADD CONSTRAINT legal_entity_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE monitored_case ADD CONSTRAINT monitored_case_case_id FOREIGN KEY (case_id) REFERENCES "case" (id);
ALTER TABLE monitored_case ADD CONSTRAINT monitored_case_created_by_user_id FOREIGN KEY (created_by) REFERENCES "user" (id);
ALTER TABLE monitored_case ADD CONSTRAINT monitored_case_legal_entity_id_legal_entity_id FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id);
ALTER TABLE monitored_case ADD CONSTRAINT monitored_case_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE monitoring_update ADD CONSTRAINT monitoring_update_monitored_case_id_monitored_case_id FOREIGN KEY (monitored_case_id) REFERENCES monitored_case (id);
ALTER TABLE notification_event ADD CONSTRAINT notification_event_recipient_user_id_user_id FOREIGN KEY (recipient_user_id) REFERENCES "user" (id);
ALTER TABLE notification_event ADD CONSTRAINT notification_event_template_id_notification_template_id FOREIGN KEY (template_id) REFERENCES notification_template (id);
ALTER TABLE permission ADD CONSTRAINT permission_role_value_role_value FOREIGN KEY (role_value) REFERENCES "role" (value);
ALTER TABLE probabilistic_estimate ADD CONSTRAINT probabilistic_estimate_case_id_case_id FOREIGN KEY (case_id) REFERENCES "case" (id);
ALTER TABLE probabilistic_estimate ADD CONSTRAINT probabilistic_estimate_created_by_user_id FOREIGN KEY (created_by) REFERENCES "user" (id);
ALTER TABLE probabilistic_estimate ADD CONSTRAINT probabilistic_estimate_legal_entity_id_legal_entity_id FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id);
ALTER TABLE probabilistic_estimate ADD CONSTRAINT probabilistic_estimate_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE scheduled_job ADD CONSTRAINT scheduled_job_reference_id_fk FOREIGN KEY (reference_id) REFERENCES monitored_case (id);
ALTER TABLE tenant_case_counter ADD CONSTRAINT tenant_case_counter_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);
ALTER TABLE tenant ADD CONSTRAINT tenant_subscription_plan_id_subscription_plan_id FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id);
ALTER TABLE user_session ADD CONSTRAINT user_session_user_id_fk FOREIGN KEY (user_id) REFERENCES "user" (id);
ALTER TABLE "user" ADD CONSTRAINT user_tenant_id_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant (id);

-- ============ COMMENTS ============
COMMENT ON COLUMN notification_template.name IS 'Internal identifier (password_reset, monitoring_update, etc.)';
COMMENT ON COLUMN notification_template.subject IS 'Email subject template with placeholders';
COMMENT ON COLUMN notification_template.body_template IS 'Email body template (HTML/text with placeholders)';
COMMENT ON COLUMN subscription_plan.name IS 'Display name (e.g. Basic, Advanced)';
COMMENT ON COLUMN subscription_plan.price_cents IS 'Monthly/annual price in euro cents';
COMMENT ON COLUMN subscription_plan.max_users IS 'Max users per tenant';
COMMENT ON COLUMN subscription_plan.max_monitored_cases IS 'Max active monitored cases';
COMMENT ON COLUMN subscription_plan.features IS 'Feature flags for plan-specific capabilities';
COMMENT ON COLUMN subscription_plan.stripe_price_id IS 'Stripe Price object ID';
COMMENT ON COLUMN monitoring_update.summary IS 'AI-generated summary of the update run';
COMMENT ON COLUMN monitoring_update.content IS 'Structured updates: [{title, source, reference, relevance, url}]';
COMMENT ON COLUMN tenant_case_counter.tenant_id IS 'FK + PK to tenant.id';
COMMENT ON COLUMN tenant_case_counter.last_number IS 'Last allocated case number for the tenant';
COMMENT ON COLUMN scheduled_job.job_type IS 'monitoring_update, estimate_recalculation, source_ingestion';
COMMENT ON COLUMN scheduled_job.reference_id IS 'ID of the entity being processed (monitored_case.id)';
COMMENT ON COLUMN scheduled_job.status IS 'pending, running, completed, failed';
COMMENT ON TABLE scheduled_job IS 'Tracks execution of async jobs: monitoring runs, estimate recalculations, etc.';
COMMENT ON COLUMN chat_message.sources IS 'Array of cited legal sources: [{title, reference, url}]';
COMMENT ON COLUMN chat_message.token_count IS 'Token usage for billing/monitoring';
COMMENT ON COLUMN chat_message.processing_time_ms IS 'RAG pipeline latency in ms';
COMMENT ON COLUMN chat_message.attachments IS 'Inline attachments: [{document_id, file_name}]';
COMMENT ON COLUMN "role".value IS 'Role identifier (admin, lawyer, etc.)';
COMMENT ON COLUMN "role".is_system IS 'System roles cannot be deleted';
COMMENT ON COLUMN "case".case_number IS 'Sequential per-tenant (#001, #002...)';
COMMENT ON COLUMN "case".deleted_at IS 'Soft delete';
COMMENT ON COLUMN tenant.name IS 'Organization / Studio name';
COMMENT ON COLUMN tenant.vat_number IS 'Partita IVA';
COMMENT ON COLUMN tenant.fiscal_code IS 'Codice fiscale azienda';
COMMENT ON COLUMN tenant.stripe_customer_id IS 'Stripe Customer object ID';
COMMENT ON COLUMN tenant.stripe_subscription_id IS 'Stripe Subscription object ID';
COMMENT ON COLUMN tenant.subscription_status IS 'Mirrors Stripe subscription status';
COMMENT ON COLUMN tenant.deleted_at IS 'Soft delete';
COMMENT ON COLUMN stripe_webhook_event.stripe_event_id IS 'Stripe event ID for idempotency';
COMMENT ON COLUMN stripe_webhook_event.event_type IS 'e.g. invoice.paid, customer.subscription.updated';
COMMENT ON TABLE stripe_webhook_event IS 'Idempotent webhook processing. Keeps full Stripe event payload for debugging.';
COMMENT ON COLUMN chat_session.case_id IS 'Optional: chat within a specific case context';
COMMENT ON COLUMN chat_session.legal_entity_id IS 'Optional: chat within a specific case context';
COMMENT ON COLUMN chat_session.title IS 'Auto-generated or user-defined session title';
COMMENT ON COLUMN chat_session.context_snapshot IS 'Frozen copy of user profile + legal entities at session start';
COMMENT ON COLUMN chat_session.deleted_at IS 'Soft delete';
COMMENT ON COLUMN monitored_case.scenario IS 'Natural language description of monitoring scenario';
COMMENT ON COLUMN monitored_case.deleted_at IS 'Soft delete';
COMMENT ON COLUMN probabilistic_estimate.case_id IS 'Optional: linked to a specific case';
COMMENT ON COLUMN probabilistic_estimate.description IS 'Natural language case description';
COMMENT ON COLUMN probabilistic_estimate.score IS 'Probability score 0.0 to 1.0';
COMMENT ON COLUMN probabilistic_estimate.analysis IS 'AI-generated reasoning and explanation';
COMMENT ON COLUMN probabilistic_estimate.sources IS 'Cited sources: [{title, reference, court, date, url}]';
COMMENT ON COLUMN probabilistic_estimate.deleted_at IS 'Soft delete';
COMMENT ON COLUMN legal_entity.name IS 'Full name (individual) or company name';
COMMENT ON COLUMN legal_entity.surname IS 'Only for individuals';
COMMENT ON COLUMN legal_entity.fiscal_code IS 'Codice fiscale';
COMMENT ON COLUMN legal_entity.vat_number IS 'Partita IVA legal entities only';
COMMENT ON COLUMN legal_entity.notes IS 'Additional context for AI';
COMMENT ON COLUMN legal_entity.deleted_at IS 'Soft delete';
COMMENT ON COLUMN user_session.id IS 'Session token / JWT jti';
COMMENT ON COLUMN estimate_history.previous_score IS 'Score before this recalculation';
COMMENT ON COLUMN estimate_history.score_delta IS 'Absolute change from previous: score - previous_score';
COMMENT ON COLUMN estimate_history.is_significant_change IS 'True if change triggered notification';
COMMENT ON COLUMN notification_event.context IS 'Template rendering context data';
COMMENT ON COLUMN "user".password_hash IS 'Nullable for SSO-only users';
COMMENT ON COLUMN "user".auth_provider_id IS 'External provider user ID (Google sub, etc.)';
COMMENT ON COLUMN "user".professional_role IS 'Attorney, Accountant, Tax Consultant...';
COMMENT ON COLUMN "user".about IS 'Free-text expertise description fed into AI context';
COMMENT ON COLUMN "user".profile_completion_pct IS '0-100 profile completion';
COMMENT ON COLUMN "user".deleted_at IS 'Soft delete';
COMMENT ON COLUMN document.legal_entity_id IS 'Optional: document linked to a client';
COMMENT ON COLUMN document.case_id IS 'Optional: document linked to a case';
COMMENT ON COLUMN document.storage_key IS 'S3 object key or storage path';
COMMENT ON COLUMN document.embedding_id IS 'Vector store reference ID after indexing';
COMMENT ON COLUMN document.embedding_error IS 'Error message if indexing failed';
COMMENT ON COLUMN document.indexed_at IS 'When embedding completed';
COMMENT ON COLUMN document.metadata IS 'Extensible metadata (page count, language, tag, etc.)';
COMMENT ON COLUMN document.deleted_at IS 'Soft delete';
